language: java
jdk:
- openjdk8

script: "mvn deploy --settings settings.xml"
env:
  global:
  - secure: "DY+dOd0Gz236ybU/s+6XyXD+JsjPEMkm4pozMwq6s5vI+hugPKF6v9vQtu/YJ1KV4fVPC5ZnNhmbx+qoUYtKNaC6W96h8UR7QUvC1WfWAp1/Epr6GSgqKn80mqD7Q+sUisUWRLf0l3xQvuVQqmPzcMOgIaIZfKn6VrPMS242GpFOsyK1Vuoyn3uOOmBuxeDQLfuYQRAsCqsWUQsC6QRD1rD1+zcqZo42rripvWIxsPVtMv15Hp8KuE1bl1Or/xCIv8JeSottw+6/hrjIAB0ewZ/kJwvMOxiQltfy9PY+NAHmVuX2hmnzS5BWEcDrRuBh1vHANGzIH3Jad8gwO7epiIykFU2CbpTkZ1htJeXDB9dSx311TTHBK6bZhHJJxaqeoNpWpS9Um9CkuWUC1s7tvmR5AwuMezyhgI3Luq71R17GnsseFxfrBOrJpJX0MTIAyU8PZm0zTmM0MW2fjaXmApw8InQOSBaVp+4WkoAAP1q6B3lcOThnhtgCZ+oR2zTnVxEVrV3pSpLwXQWlr+u8Zbwh4bFP39fwZZiYXnHRr9E0Ie2/nSQTF/JcewfgHQ/oo6oNJqgnCYTLuYKaSr9H0r2oTexyfcT3/arbTg6bDnqpcvuFYsA/8uPLrMKQ2QdOwRiIniCUoXhTe23fNOeZPcz682ndP8DuIx6e9saXT7M="
  - secure: "miJ6x2bqw/zy/6kYBA+s8HjFqy5m7D69LsD9TSa8EjVoEt7IGUOdevjAAyxba7RBmXUSq/bXiQa6DDkqb2Eb4lq/nucKO4Ub766+6Ci4Rcfp0c/QYjKDbZGthfEfe1imH8Y2u5b4Q7t/Vfmwktg7XagZ8ixD/n5/P0/gosjIiUE6Clw8sp3YZCtAUmS7Qq46q6yUkH2INNj0Q3biXmBdiVxO5RMqwcCipJSU/SdCRwrJmDoQaKx0YerKeQUHqNQ4J4u776+eIu3zotaVzw36kJieLrekkBNYqbLHK6MbcoKX70J09KFirRwoY4YGNLAal179rQpyZ6zWWokH+jfKTiez1pCb4zSxXYXFnn9hfYN2GC8oUrs87lrm1foZ6HtKag2d8GbdxYOTKXiuFGxwBJUad0As0jH81c5SCIYbzs2vfddb70p8fhDWWrs1Y6IcGgR8vcTwMvjIrOPSSLs3ERCZ+e+PGXLvy/HsKtFzXPC26pwvSfgYeSVJDs59ltNGbdfDmAItiLfQdPh2piPouYS61FaWpaO0Y3shI9HFpWL2eARe2b5cfbK9MMAn4/zV+AepsuGwXoOrHpqLH+B2CUFm1tuE9MegLry0jOjFs/NUnwpQb7KvE+3OF9uDR2R8j8DfUMuMqQygqm+18xtVvodfT/f0yOiiQNJ4lccMuJ8="
deploy:
  provider: releases
  api_key: 
    secure: "ruzHebe4wUDA1Rz5xwsOM9Kb3BuA57wvRDHLi5zL8u8SsRQwgBVtzgi6i8fOHu2trbVjmYMs/1dCjI09qW684FX3CWFC8QqE4MD73phwej+EQKVINwCBnAVbQ/RudK5LmkjhAHNuYjMnk33qT3ASQDFBb3LUVBTXqwQC2B5Ll2t+o7Zcsd8na/4loRNtor16kl7Rxj3s9jCKsRQAWA5wfOPVEDSZC3JVEroIytDF8avP1icTd+0m5vWvMh+BQbUvnuiU9n//U6Vc70jydo9EmTGF6PIQ978mbAbEbhcjiAyH9xJ9z8GOWc31JZS0OQfTNOwGpAk0euE0VHvMZ0tV/jICCpAOX5k5LJkK02jXkWZ/sARpC5aCx5cu8nSSuMhlCgqqXMq1WjdQlG76JtO2VOW/z+A4tsW3rlJ+sanAZxFby2ukgJRVPPwxjUIMS8ZfqskKN6SEXo/3IQrcIWCEUUQ0QbGjmsUBvJqQzad6lP2Uylt9ICCczuVcng1exUk64sbS5fcDdrsjmxVEcmEQJ3wGxeHDK3Lhtk6NxdItqlsOnXgeAA75b+Gix/A9VUb2PIU7Xq/CIytV+iBxuYsbTyS3E4M/ZFgSOjB/xNZz+3nzfvXQDsvbRxCX2uSYBfChKmRDAwJjsFkKI4lG624bUzj1feMcuv7p/31mOdwREyI="
  file_glob: true
  file: 
    - "target/MapManager_v*.jar"
  skip_cleanup: true
  on:
    tags: true
